//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuihuo
    {
        public string no { get; set; }
        public string sno { get; set; }
        public int num { get; set; }
        public string tuidate { get; set; }
        public string jbr { get; set; }
        public string spr { get; set; }
        public decimal tkje { get; set; }
    
        public virtual shangpin shangpin { get; set; }
        public virtual shouhuo shouhuo { get; set; }
    }
}
