//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class gy
    {
        public string gname { get; set; }
        public string glxr { get; set; }
        public string glxfs { get; set; }
        public string bz { get; set; }
    }
}
