//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupermarketEntities : DbContext
    {
        public SupermarketEntities()
            : base("name=SupermarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<guoqishanpin> guoqishanpins { get; set; }
        public virtual DbSet<gy> gys { get; set; }
        public virtual DbSet<jinhuo> jinhuos { get; set; }
        public virtual DbSet<shangpin> shangpins { get; set; }
        public virtual DbSet<shouhuo> shouhuos { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
