//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class shangpin
    {
        public shangpin()
        {
            this.jinhuos = new HashSet<jinhuo>();
            this.shouhuos = new HashSet<shouhuo>();
        }
    
        public string sno { get; set; }
        public string sname { get; set; }
        public string sdate { get; set; }
        public string sleibie { get; set; }
        public string sjinjia { get; set; }
        public string sshoujia { get; set; }
        public string sdanwei { get; set; }
        public string sbaozhiqi { get; set; }
        public int shave { get; set; }
    
        public virtual guoqishanpin guoqishanpin { get; set; }
        public virtual ICollection<jinhuo> jinhuos { get; set; }
        public virtual ICollection<shouhuo> shouhuos { get; set; }
    }
}
