//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jinhuo
    {
        public string no { get; set; }
        public string sno { get; set; }
        public int snum { get; set; }
        public decimal price { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
        public string date3 { get; set; }
        public string scome { get; set; }
        public string sperson { get; set; }
    
        public virtual shangpin shangpin { get; set; }
    }
}
